dirs:
  - ./docs            # or "." if you want the whole repo
excludedDirs:
  - ./build
  - ./.vercel
  - ./.docusaurus
  - ./node_modules
useGitIgnore: true
followRedirects: true

ignorePatterns:
  - pattern: '^http(s)?://localhost'
  - pattern: '^http(s)?://127.0.0.1'
  - pattern: '^http(s)?://gitlab.com/ConsenSys/'
  - pattern: '^http(s)?://github.com/ConsenSys/orchestrate'
  - pattern: '^http(s)?://github.com/INFURA/docs(?:/(issues|pulls))?'
  - pattern: '^http(s)?://consensys.net'
  - pattern: '{{[a-zA-Z_\-\.\[\]'']+}}'
  - pattern: '^https?://[a-zA-Z0-9.-]*\.infura\.io/v3/.*$'
  - pattern: '^http(s)?://.+.zendesk.com'
  - pattern: '^http(s)?://.+.etherscan.io'
  - pattern: '^http(s)?://help.figma.com'
  - pattern: 'http(s)?://.+\&\#39\;'
  - pattern: "http(s)?://.+'"

httpHeaders:
  - url:
      - https://github.com/
      - https://guides.github.com/
      - https://help.github.com/
      - https://docs.github.com/
    headers:
      Accept-Encoding: zstd, br, gzip, deflate

aliveStatusCodes:
  - 200
  - 206
  - 403
